/** @jsxImportSource theme-ui */
import Head from "next/head"

import { Heading, Text } from "@theme-ui/components"

import Header from "@/components/Header/Header"
import { useWallet } from "@solana/wallet-adapter-react"
import { useRafflesStore } from "@/hooks/useRafflesStore"
import { useEffect, useMemo, useState } from "react"
import { Raffle } from "lib/types"

export default function Home() {
  const { publicKey } = useWallet()
  const { raffles, fetchAllRaffles, fetching } = useRafflesStore()
  const [showOwnRafflesOnly, setShowOwnRafflesOnly] = useState(false)
  const [hideEndedRaffles, setHideEndedRaffles] = useState(false)

  useEffect(() => {
    fetchAllRaffles()
  }, [fetchAllRaffles])

  const filterMap = useMemo(
    () => ({
      own: (raffle: Raffle) => raffle.entrants.has(publicKey?.toString() || ""),
      ongoing: (raffle: Raffle) => new Date() < raffle.endTimestamp,
    }),
    [publicKey]
  )

  const rafflesToShow = useMemo(() => {
    // @ts-ignore
    let toShow = [...raffles.values()].sort(
      (raffle1, raffle2) =>
        raffle2.endTimestamp.getTime() - raffle1.endTimestamp.getTime()
    )
    if (showOwnRafflesOnly) toShow = toShow.filter(filterMap.own)
    if (hideEndedRaffles) toShow = toShow.filter(filterMap.ongoing)
    return toShow
  }, [raffles, filterMap, showOwnRafflesOnly, hideEndedRaffles])

  console.log(rafflesToShow)
  return (
    <>
      <Head>
        <title>Raffles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main
        sx={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          marginTop: "4rem",
        }}
      >
        <Heading mb=".8rem" variant="heading1">
          Raffles template
        </Heading>
        <Text>Our raffles</Text>
      </main>

      <footer
        sx={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          margin: "4rem 0",
        }}
      >
        Powered by
        <a
          href="https://twitter.com/mentaworks"
          target="_blank"
          rel="noopener noreferrer"
          sx={{
            display: "flex",
            alignItems: "center",
            marginLeft: "0.2em",
          }}
        >
          <Text
            variant="small"
            sx={{
              display: "flex",
              alignItems: "center",
            }}
          >
            menta.works
          </Text>
        </a>
      </footer>
    </>
  )
}
